{
    'name': 'Tailor Management',
    'version': '1.0',
    'category': 'Services',
    'summary': 'Tailor business management system',
    'description': 'Custom module for managing tailoring operations',
    'author': 'Denyse Ashimwe',
    'license': 'LGPL-3',

    'depends': ['base', 'mail', 'portal', 'website', 'sale', 'account'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'data/email_template.xml',
        'views/res_partner_views.xml',
        'views/tailor_order_views.xml',
        'views/portal_orders.xml',
        'report/tailor_order_report.xml',
        'views/sale_order_view.xml',
        'views/dashboard_view.xml',
        'views/showroom_dashboard.xml',
        'views/production_dashboard.xml',
        'views/financial_reports.xml',
    ],
    'installable': True,
    'application': True,
}